# =============================================================================
# First OFF-BOW Julia↔Fortran PARITY — Stillwater, Oklahoma (semi-arid SP run,
# use_cn=false). Injects the Fortran before_step_n1 dump into a Stillwater Julia
# inst, runs ONE clm_drv! biogeophysics step, and diffs the prognostic state
# against the Fortran after_hydrologydrainage_n1 dump.
#
# Reference dumps generated by the instrumented cesm.exe (restFile_write_dump)
# from a Stillwater cold-start at 2002-01-01 (nstep 0). The forcing file starts
# 2002-01-01 01:00, so the step that yields nstep N reads the (base+N h) record.
# Stillwater is UTC-6, so nstep ~13–23 (UTC) is local daytime; the default
# nstep=18 is local midday.
#
# The Stillwater subgrid is col=1/pft=4 (Fortran) vs Julia nc=2/np=5 (the benign
# "always create lake" phantom column, ISTDLAK ltype=5 — same as Bow). The
# parity diffs column 1 (natveg) + the natveg patches, exactly like the Bow
# harness; the phantom lake column/patch is injected as default and ignored.
#
# RESULT (this is the FIRST off-Bow Julia↔Fortran parity):
#   The single-step parity is now < 1e-2 at EVERY nstep EXCEPT nstep 1 — most steps
#   are ~1e-7 (machine precision). Representative:
#     nstep 4/10/17 (snow accum): 5.5e-8 / 4.4e-8 / 4.2e-6
#     nstep 2 (bareground):       1.3e-5
#     nstep 18 (day):             1.68e-5  (T_GRND/SNOW_DEPTH exact, T_VEG 8.0e-6)
#     nstep 1 (night):            2.2e-2   (T_VEG — see below)
#
# THE nstep-1 RESIDUAL IS A COLD-START INITIALIZATION ARTIFACT, NOT A MODEL ERROR —
# and NOT one we should "fix" by matching Fortran. The dumps show Fortran does not
# update T_VEG on its literal first timestep: before_step_n1 T_VEG = after_n1 T_VEG =
# 280.6 (the cold-start IC, unchanged — Fortran's exposed/noexposed-veg flux filters
# are both empty on step 1, so no patch is processed). It then sets T_VEG = forc_t at
# nstep 2 (bareground) and only solves the canopy energy balance from nstep 3 (266.8).
# Julia solves the canopy on step 1, so its veg-patch T_VEG = 268 K — the correct
# nocturnal energy-balance value, within ~1 K of the converged temperature Fortran
# itself reaches at n3. So Fortran's 280.6 contains NO canopy physics (it's an
# uninitialized IC); Julia's 268 is physically correct. Making Julia output 280.6
# would mean reproducing a non-physical initialization artifact — degrading a correct
# canopy temperature to match an IC for one step — so we DELIBERATELY do not. The
# canopy solve itself is exact (nstep 18 T_VEG 8e-6) and the difference washes out by
# nstep 3 (multi-step free-run: T_VEG 2.2e-2 @n1 → 2.8e-2 @n2 → <1.5e-3 @n3 → 5e-4 @n6).
# Bottom line: n1 is an initialization comparison, not a physics comparison; the 2.2e-2
# reflects Julia being MORE correct, not less. Left honest and documented.
# RESOLVED RESIDUALS:
#   - H2OSOI_LIQ/ICE 15–23% (daytime) — was a FORCING-RECORD off-by-one. Fortran
#     reads the forcing at the START of the step interval (the step that yields
#     nstep N uses base+(N-1)h); the harness read base+(N)h → a one-hour-late FSDS
#     (nstep 18: 505.6 vs the correct 412.2 W/m²) → +22.7% incident solar → SABV
#     *and* SABG uniformly 1.227× high (the two-stream/albedo were exact all along).
#     Fixed via force_date=base+Hour(max(N-1,1)).
#   - SNOW_DEPTH ~1.8% + the residual H2OSOI — was an INJECTION bug in
#     read_fortran_restart!. For a no-snow-layer column (snl==0) it RECOMPUTED
#     h2osno_no_layers by summing the snow-layer slots h2osoi_{liq,ice}[1,1:nlevsno],
#     which are NOT injected for such a column → cold-start NaN → NaN h2osno_total →
#     the snow-depth kernel took its reset branch (the pack never accumulated /
#     never fully melted) and int_snow NaN'd. Fixed by injecting the dump's
#     H2OSNO_NO_LAYERS field directly. Daytime nstep 18 → 1.68e-5; the SNOW_DEPTH
#     and H2OSOI residuals both collapse. (My earlier "benign float-level artifact"
#     characterization was WRONG — it was this NaN.)
#   - NIGHT step (nstep 1) NaN — RESOLVED 2026-06-18. Root cause: read_fortran_restart!
#     injected the restart's PRE-SatellitePhenology veg structure (cold-start zeros:
#     elai=esai=htop=0) over cold_start!'s correct surfdata-derived values (elai=0.5,
#     htop=18), but left frac_veg_nosno_alb=1 → a leafless exposed-veg "canopy". The
#     z0 blend then hit log(z0mr*htop=0) → z0mv=NaN → ustar/t_veg/t_grnd=NaN. Fortran's
#     flux uses the POST-SP structure (= cold_start's values), so the fix is
#     inject_veg_struct=false (keep cold_start's surfdata veg structure). Hardening in
#     canopy_fluxes.jl: re-seed z0mv from the bare-canopy z0 (z0m_patch) each step and
#     floor it with z0mg in the log-blend. Night nstep 1 now: T_GRND 5.5e-3, T_VEG
#     4.4e-2, all finite (was NaN).
#   - SNOW_DEPTH ~5% (overnight accum) — was a MISSING bifall wind term. With h2osno
#     (snow WATER), frac_sno, frac_sno_eff, forc_t all matching Fortran exactly, only
#     bifall (new-snow density) differed (106.3 vs 111.8). Fortran's lnd_in sets
#     wind_dependent_snow_density=.true. (adds 266.861·((1+tanh(wind/fact))/2)^8.8 =
#     +5.5 at the ~1.5 m/s wind). The global Julia default keeps it FALSE (the ^8.8 is
#     AD-unfriendly: breaks the 250 K FD-vs-AD check); this harness sets it true via
#     snow_hydrology_set_control_for_testing! to match the namelist. → n4/n10/n17 5e-2
#     → ~1e-7.
#   - nstep-2 T_VEG 2.7e-2 — read_fortran_restart! now injects FRAC_VEG_NOSNO_ALB
#     (Fortran's prev-step exposed-veg flag, which ramps on over ~3 cold-start steps),
#     so Julia is bareground when Fortran's filter hasn't activated. → n2 to 1.3e-5.
#
# Usage: julia +1.12 --project=. scripts/fortran_parity_stillwater.jl
# =============================================================================
using CLM, NCDatasets, Dates, Printf

const STW   = "/Users/darri.eythorsson/compHydro/SYMFLUENCE_data/domain_Stillwater_Oklahoma"
const FS    = joinpath(STW, "settings/CLM/parameters/surfdata_clm.nc")
const FP    = joinpath(STW, "settings/CLM/parameters/clm5_params.nc")
const FFORC = joinpath(STW, "data/forcing/CLM_input/clmforc.2002.nc")
const DUMPS = "/Users/darri.eythorsson/compHydro/SYMFLUENCE_data/clm_stillwater_parity"
const SNOWOPT = "/Users/darri.eythorsson/projects/cesm-inputdata/lnd/clm2/snicardata/snicar_optics_5bnd_c013122.nc"
const SNOWAGE = "/Users/darri.eythorsson/projects/cesm-inputdata/lnd/clm2/snicardata/snicar_drdt_bst_fit_60_c070416.nc"

const _read_fortran_restart! = getfield(CLM, Symbol("read_fortran_restart!"))

function build_stillwater_inst(; start_date::DateTime)
    CLM.rooting_profile_config.rooting_profile_method_water  = CLM.JACKSON_1996_ROOT
    CLM.rooting_profile_config.rooting_profile_method_carbon = CLM.JACKSON_1996_ROOT
    # Match the Fortran lnd_in (wind_dependent_snow_density = .true.) — adds the
    # wind-densification term to new-snow bulk density. Without it bifall is ~5% low
    # at modest winds → snow_depth ~5% high (the snow water is unaffected).
    CLM.snow_hydrology_set_control_for_testing!(wind_dep_snow_density=true)
    (inst, bounds, filt, tm) = CLM.clm_initialize!(; fsurdat=FS, paramfile=FP,
        start_date=start_date, dtime=3600, use_cn=false, use_luna=false,
        use_bedrock=true, use_aquifer_layer=false, h2osfcflag=0,
        fsnowoptics=SNOWOPT, fsnowaging=SNOWAGE, int_snow_max=2000.0)
    return (inst, bounds, filt, tm)
end

# Prognostic-state registry (biogeophys; SP run has no CN pools).
function registry(inst)
    ws = inst.water.waterstatebulk_inst.ws
    wd = inst.water.waterdiagnosticbulk_inst
    [("T_SOISNO",   :col2d, () -> inst.temperature.t_soisno_col),
     ("H2OSOI_LIQ", :col2d, () -> ws.h2osoi_liq_col),
     ("H2OSOI_ICE", :col2d, () -> ws.h2osoi_ice_col),
     ("T_GRND",     :col1d, () -> inst.temperature.t_grnd_col),
     ("ZWT",        :col1d, () -> inst.soilhydrology.zwt_col),
     ("H2OSFC",     :col1d, () -> ws.h2osfc_col),
     ("SNOW_DEPTH", :col1d, () -> wd.snow_depth_col),
     ("T_VEG",      :patch, () -> inst.temperature.t_veg_patch)]
end

function diff_field(jl, ds, name, kind)
    haskey(ds, name) || return (NaN, 0)
    f = ds[name]
    mx = 0.0; n = 0
    if kind == :col1d
        v = ismissing(f[1]) ? NaN : Float64(f[1])
        isnan(v) && return (NaN, 0)
        return (abs(Float64(jl[1]) - v) / (1 + abs(v)), 1)
    elseif kind == :col2d
        d = f[:, 1]                      # (levtot, column=1)
        for j in 1:min(length(d), size(jl, 2))
            fv = ismissing(d[j]) ? NaN : Float64(d[j]); jv = Float64(jl[1, j])
            (isnan(fv) || isnan(jv)) && continue
            mx = max(mx, abs(jv - fv) / (1 + abs(fv))); n += 1
        end
    else # patch: compare the natveg patches (Fortran pft order = Julia first N)
        d = f[:]
        for p in 1:min(length(d), length(jl))
            fv = ismissing(d[p]) ? NaN : Float64(d[p]); jv = Float64(jl[p])
            (isnan(fv) || isnan(jv)) && continue
            mx = max(mx, abs(jv - fv) / (1 + abs(fv))); n += 1
        end
    end
    return (mx, n)
end

function main(; nstep::Int = 18)
    base = DateTime(2002, 1, 1)             # Fortran nstep-0 date
    step_date = base + Hour(nstep - 1)      # state at start of the step (nstep-1)
    # Fortran reads the forcing at the START of the step interval: the step that
    # yields nstep N integrates (N-1)→N and uses the record at base+(N-1)h. The
    # clmforc file starts 01:00 (rec 1), so nstep 1 (interval 00:00→01:00, start
    # 00:00) clamps to rec 1. The previous base+Hour(nstep) read the END-of-interval
    # record → a one-hour-late FSDS (e.g. nstep 18: 505.6 vs the correct 412.2 W/m²)
    # → +23% absorbed solar → spurious top-layer melt (H2OSOI_LIQ/ICE 15–23%).
    force_date = base + Hour(max(nstep - 1, 1))
    (inst, bounds, filt, tm) = build_stillwater_inst(; start_date=step_date)
    @printf("Stillwater inst: nc=%d np=%d  PFTs=%s\n", bounds.endc, bounds.endp, string(Int.(inst.patch.itype)))

    bdump = joinpath(DUMPS, "pdump_before_step_n$(nstep).nc")
    # The Stillwater restart dumps carry the PRE-SatellitePhenology veg structure
    # (zeros at a cold-start step); injecting them would clobber cold_start!'s
    # surfdata-derived elai/esai/htop (which equal Fortran's in-step post-SP values
    # the flux actually uses) and leave a leafless exposed-veg canopy → t_veg NaN.
    _read_fortran_restart!(bdump, inst, bounds; inject_veg_struct=false)

    config  = CLM.CLMDriverConfig(use_cn=false, use_aquifer_layer=false,
                                  use_hydrstress=false, use_luna=false)
    filt_ia = CLM.clump_filter_inactive_and_active
    ng, nc, np = bounds.endg, bounds.endc, bounds.endp

    fr = CLM.ForcingReader(); CLM.forcing_reader_init!(fr, FFORC)
    tf = replace(FFORC, r"clmforc\.[^/]*\.nc$" => "topo_forcing.nc")
    if isfile(tf)
        dt = NCDataset(tf, "r")
        haskey(dt, "TOPO") && (ft = Float64(dt["TOPO"][1]);
            for g in 1:ng; inst.atm2lnd.forc_topo_grc[g] = ft; end;
            for c in 1:nc; inst.topo.topo_col[c] = ft; end)
        close(dt)
    end

    calday = CLM.get_curr_calday(tm); (declin, _) = CLM.compute_orbital(calday)
    (declinm1, _) = CLM.compute_orbital(calday - 3600.0/CLM.SECSPDAY)
    nextsw = calday + 3600.0/CLM.SECSPDAY
    CLM.init_daylength!(inst.gridcell, declin, declinm1, CLM.ORB_OBLIQR_DEFAULT, 1:ng)
    CLM.advance_timestep!(tm)
    CLM.read_forcing_step!(fr, inst.atm2lnd, force_date, ng, nc)
    # The clmforc reader doesn't set the atm reference heights; without them
    # forc_hgt_u/t/q=0 → zldis collapses → the M-O friction-velocity solve blows
    # up to NaN (the documented cold-start forc_hgt fix). Set them to 30 m.
    for g in 1:ng
        inst.atm2lnd.forc_hgt_u_grc[g] = 30.0
        inst.atm2lnd.forc_hgt_t_grc[g] = 30.0
        inst.atm2lnd.forc_hgt_q_grc[g] = 30.0
    end
    CLM.downscale_forcings!(bounds, inst.atm2lnd, inst.column, inst.landunit, inst.topo)
    (yr, mon, d, tod) = CLM.get_curr_date(tm)
    CLM.clm_drv!(config, inst, filt, filt_ia, bounds, true, nextsw, declin, declin,
        CLM.ORB_OBLIQR_DEFAULT, false, false, "", false;
        nstep=tm.nstep, is_first_step=true,
        is_beg_curr_day=CLM.is_beg_curr_day(tm), is_end_curr_day=CLM.is_end_curr_day(tm),
        is_beg_curr_year=CLM.is_beg_curr_year(tm), dtime=3600.0, mon=mon, day=d,
        photosyns=inst.photosyns)
    CLM.forcing_reader_close!(fr)

    edump = joinpath(DUMPS, "pdump_after_hydrologydrainage_n$(nstep).nc")
    ds = NCDataset(edump, "r")
    @printf("\n%-14s %12s %8s\n", "field", "max|rel|", "npts")
    gmax = 0.0
    for (name, kind, getter) in registry(inst)
        rel, n = diff_field(getter(), ds, name, kind)
        n == 0 && continue
        gmax = max(gmax, rel)
        @printf("%-14s %12.3e %8d\n", name, rel, n)
    end
    close(ds)
    @printf("\nSTILLWATER single-step parity: global max|rel| = %.3e\n", gmax)
    return gmax
end

main()
