# =============================================================================
# fortran_parity_cn_autumn.jl — CN/BGC single-step parity over the AUTUMN /
# leaf-offset window at Bow (the window the summer suite was structurally
# blind to).
#
# WHY THIS WINDOW
# ---------------
# Bow's PFTs are 0 (bare), 1 (needleleaf evergreen tree -> evergreen phenology)
# and 12 (C3 arctic grass -> season_decid = 1). The seasonal-deciduous leaf
# OFFSET is triggered by `dayl < crit_dayl` past the summer solstice, and the
# litterfall ramp then runs for `ndays_off` days (CNPhenologyMod.F90:1183-1185).
#
# PR #206 found that the CN phenology params were NEVER read from the params
# file: `ndays_off` ran at Fortran's *unit-test* default of 30 d instead of the
# file's 15 d -- a 2x-too-long / 2x-too-weak litterfall ramp. A summer-only
# validation window CANNOT SEE that (offset_flag == 0 all summer).
#
# The Fortran reference (bgc_ref_autumn, generated by the restored
# restFile_write_dump instrumentation) fires offset at nstep 1759931
# (2202-10-10 10:00) with offset_counter = 15.0 d exactly, and the ramp ends at
# nstep 1760291 (2202-10-25 10:00). That is the ground truth for ndays_off = 15.
#
# WHAT THIS DOES
# --------------
# For each probe nstep: inject the Fortran `before_step` dump as the shared IC,
# run ONE use_cn clm_drv! step, and diff the post-step state against the
# `after_hydrologydrainage` dump (which is AFTER EcosystemDynamicsPreDrainage --
# i.e. post-CN-pool-update -- but BEFORE PostDrainage/leaching).
#
#   *** METHODOLOGY TRAP (banked): CN probes MUST diff against
#   *** after_hydrologydrainage, NOT before_step. before_step holds the PREVIOUS
#   *** step's values for the allocation-pipeline fields.
#
#   julia +1.12 --project=. scripts/fortran_parity_cn_autumn.jl
# =============================================================================
include(joinpath(@__DIR__, "fortran_parity_common.jl"))

const AUT_DIR  = "/Users/darri.eythorsson/compHydro/SYMFLUENCE_data/clm_bgc_spinup/bgc_ref_autumn"
const AUT_BASE = 1753153            # nstep -> DateTime(2202,1,1) + Hour(n - BASE)
const TRIGGER  = 1759931            # 2202-10-10 10:00 : offset_flag 0 -> 1
const RAMP_END = 1760291            # 2202-10-25 10:00 : offset_flag 1 -> 0

# Probe steps: pre-trigger, the trigger step itself, through the ramp, the ramp
# end step, and post-ramp dormancy.
const PROBES = [
    (1759900, "pre-trigger (10-09 03:00)"),
    (1759930, "step BEFORE trigger (10-10 09:00)"),
    (TRIGGER, "TRIGGER STEP (10-10 10:00)"),
    (1759945, "ramp d0.6 (10-11 00:00)"),
    (1760017, "ramp d3.6 (10-14 00:00)"),
    (1760113, "ramp d7.6 (10-18 00:00)"),
    (1760233, "ramp d12.6 (10-23 00:00)"),
    (1760290, "step BEFORE ramp end (10-25 09:00)"),
    (RAMP_END, "RAMP END STEP (10-25 10:00)"),
    (1760353, "post-ramp dormant (10-28 00:00)"),
]

# Patch-level CN state (carbon)
const PATCH_C = ("leafc","leafc_storage","leafc_xfer","frootc","frootc_storage","frootc_xfer",
                 "livestemc","deadstemc","livecrootc","deadcrootc","cpool","xsmrpool",
                 "gresp_storage","leafcmax")
# Patch-level CN state (nitrogen)
const PATCH_N = ("leafn","leafn_storage","leafn_xfer","frootn","frootn_storage","frootn_xfer",
                 "deadstemn","livestemn","retransn","npool")
# Phenology state — THE point of this window
const PHENO   = ("offset_flag","offset_counter","onset_flag","onset_counter","dormant_flag",
                 "days_active","prev_leafc_to_litter","prev_frootc_to_litter",
                 "offset_fdd","offset_swi","onset_gdd","onset_gddflag")

_rel(f, j) = abs(f - j) / (1.0 + max(abs(f), abs(j)))

function score_step(nstep::Int, label::String)
    bdump = joinpath(AUT_DIR, "pdump_before_step_n$(nstep).nc")
    edump = joinpath(AUT_DIR, "pdump_after_hydrologydrainage_n$(nstep).nc")
    (isfile(bdump) && isfile(edump)) || (println("  dumps missing for n$nstep"); return nothing)

    inst, bounds = run_one_parity_step!(nstep; use_cn=true, dumpdir=AUT_DIR,
        use_hydrstress=true, use_luna=true,
        step_date=DateTime(2002,1,1) + Hour(nstep - AUT_BASE),
        forcing_file=replace(FFORCING, "clmforc.2003.nc" => "clmforc.2002.nc"))

    ccs = inst.bgc_vegetation.cnveg_carbonstate_inst
    cns = inst.bgc_vegetation.cnveg_nitrogenstate_inst
    cvs = inst.bgc_vegetation.cnveg_state_inst
    cfx = inst.bgc_vegetation.cnveg_carbonflux_inst
    scs = inst.soilbiogeochem_carbonstate
    sns = inst.soilbiogeochem_nitrogenstate

    ds = NCDataset(edump, "r")
    jl_pfts = Int.(inst.patch.itype); f_pfts = Int.(ds["pfts1d_itypveg"][:])
    # Julia builds 2 cols / 4 patches; Fortran has 1 col / 3 pfts. Only the
    # COLUMN-1 patches correspond. Patch 4 lives on column 2 (a landunit with no
    # CN state -> spval 1e36); mapping it onto a Fortran patch by pft type alone
    # manufactures a bogus 1e36 diff. Restrict to column 1.
    jl_cols = Int.(inst.patch.column)
    jl2f = Dict{Int,Int}()
    for pj in eachindex(jl_pfts)
        jl_cols[pj] == 1 || continue
        for pf in eachindex(f_pfts)
            if f_pfts[pf] == jl_pfts[pj] && !haskey(jl2f, pj); jl2f[pj] = pf; end
        end
    end

    rows = Tuple{String,Float64,Float64}[]
    function patchcmp(name, jlarr)
        d = _dumpvar(ds, name); d === nothing && return
        ma = 0.0; mr = 0.0
        for pj in 1:min(length(jlarr), length(jl_pfts))
            haskey(jl2f, pj) || continue
            fv = d[jl2f[pj]]; jv = Float64(jlarr[pj])
            (isnan(fv) && isnan(jv)) && continue
            (abs(fv) > 1e30 || abs(jv) > 1e30) && continue   # spval guard
            ma = max(ma, abs(fv - jv)); mr = max(mr, _rel(fv, jv))
        end
        push!(rows, (name, ma, mr))
    end
    function poolcmp(name, arr3, pidx)
        d = _dumpvar(ds, name); d === nothing && return
        nl = min(length(d), size(arr3, 2)); ma = 0.0; mr = 0.0
        for j in 1:nl
            fv = d[j]; jv = Float64(arr3[1, j, pidx])
            (isnan(fv) && isnan(jv)) && continue
            ma = max(ma, abs(fv - jv)); mr = max(mr, _rel(fv, jv))
        end
        push!(rows, (name, ma, mr))
    end
    function col2cmp(name, arr)
        d = _dumpvar(ds, name); d === nothing && return
        nl = min(length(d), size(arr, 2)); ma = 0.0; mr = 0.0
        for j in 1:nl
            fv = d[j]; jv = Float64(arr[1, j])
            (isnan(fv) && isnan(jv)) && continue
            ma = max(ma, abs(fv - jv)); mr = max(mr, _rel(fv, jv))
        end
        push!(rows, (name, ma, mr))
    end

    for s in PATCH_C
        f = Symbol(s * "_patch"); hasproperty(ccs, f) && patchcmp(s, getfield(ccs, f))
    end
    for s in PATCH_N
        f = Symbol(s * "_patch"); hasproperty(cns, f) && patchcmp(s, getfield(cns, f))
    end
    for s in PHENO
        f = Symbol(s * "_patch")
        if hasproperty(cvs, f); patchcmp(s, getfield(cvs, f))
        elseif hasproperty(cfx, f); patchcmp(s, getfield(cfx, f))
        end
    end
    for (vn, p) in ("litr1c_vr"=>1, "litr2c_vr"=>2, "litr3c_vr"=>3, "soil1c_vr"=>4,
                    "soil2c_vr"=>5, "soil3c_vr"=>6, "cwdc_vr"=>7)
        poolcmp(vn, scs.decomp_cpools_vr_col, p)
    end
    for (vn, p) in ("litr1n_vr"=>1, "litr2n_vr"=>2, "litr3n_vr"=>3, "soil1n_vr"=>4, "cwdn_vr"=>7)
        poolcmp(vn, sns.decomp_npools_vr_col, p)
    end
    col2cmp("sminn_vr", sns.sminn_vr_col)
    col2cmp("smin_no3_vr", sns.smin_no3_vr_col)
    col2cmp("smin_nh4_vr", sns.smin_nh4_vr_col)

    # The headline phenology numbers, side by side (grass = Fortran patch 3)
    gj = findfirst(==(12), jl_pfts)
    gf = get(jl2f, gj === nothing ? -1 : gj, 3)
    f_of = Float64(ds["offset_flag"][gf]); f_oc = Float64(ds["offset_counter"][gf])
    f_lc = Float64(ds["leafc"][gf])
    j_of = Float64(cvs.offset_flag_patch[gj]); j_oc = Float64(cvs.offset_counter_patch[gj])
    j_lc = Float64(ccs.leafc_patch[gj])
    close(ds)

    gmax = isempty(rows) ? 0.0 : maximum(r[3] for r in rows)
    return (; label, nstep, rows, gmax,
            f_of, j_of, f_oc, j_oc, f_lc, j_lc)
end

function main()
    println("="^92)
    println("CN/BGC AUTUMN (leaf-offset) PARITY — Bow at Banff, model yr 2202")
    println("Fortran ref: bgc_ref_autumn (restFile_write_dump, 444 vars)")
    println("Grass patch pft=12 season_decid: Fortran offset fires n$TRIGGER (10-10 10:00),")
    println("offset_counter = 15.0 d  =>  ndays_off = 15 (params file), NOT 30 (unit-test default).")
    println("="^92)

    results = Any[]
    for (n, lab) in PROBES
        println("\n--- n$n  $lab")
        r = try
            score_step(n, lab)
        catch e
            println("  !!! CRASHED: "); Base.showerror(stdout, e); println()
            nothing
        end
        r === nothing && continue
        push!(results, r)
        @printf("  phenology   Fortran            Julia\n")
        @printf("    offset_flag     %6.1f           %6.1f   %s\n", r.f_of, r.j_of,
                r.f_of == r.j_of ? "MATCH" : "*** MISMATCH ***")
        @printf("    offset_counter  %9.2f d       %9.2f d   %s\n", r.f_oc/86400, r.j_oc/86400,
                abs(r.f_oc - r.j_oc) < 1.0 ? "MATCH" : "*** MISMATCH ***")
        @printf("    leafc (grass)   %9.4f         %9.4f   rel %.2e\n", r.f_lc, r.j_lc, _rel(r.f_lc, r.j_lc))
        @printf("  CN state global max|rel| = %.3e   (%d fields)\n", r.gmax, length(r.rows))
        worst = sort(r.rows, by = x -> -x[3])[1:min(5, length(r.rows))]
        for (nm, a, rl) in worst
            @printf("      %-22s abs %10.3e  rel %10.3e %s\n", nm, a, rl, rl > 1e-6 ? "" : "ok")
        end
    end

    println("\n" * "="^92)
    println("SUMMARY — autumn window")
    @printf("  %-32s %10s %10s %8s %8s\n", "probe", "max|rel|", "leafc rel", "offFlag", "offCnt")
    println("  " * "-"^76)
    for r in results
        @printf("  %-32s %10.3e %10.3e %8s %8s\n", r.label, r.gmax, _rel(r.f_lc, r.j_lc),
                r.f_of == r.j_of ? "ok" : "FAIL",
                abs(r.f_oc - r.j_oc) < 1.0 ? "ok" : "FAIL")
    end
    gg = isempty(results) ? NaN : maximum(r.gmax for r in results)
    @printf("\n  AUTUMN WINDOW global CN max|rel| = %.3e\n", gg)
    return 0
end

exit(main())
